.\"                                      Hey, EMACS: -*- nroff -*-
.\" (c) 2003 Software in the Public Interest
.\" Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
.\" Está basada en la página de manual original:
.\" versión 1.2 del CVS de
.\" /cvs/debian-doc/manpages/english/auto-apt/auto-apt.1

.TH auto-apt 1 "29 de Junio de 2000"
.SH NOMBRE
auto-apt \- herramienta de instalación de paquetes por demanda
.SH SINOPSIS
.B auto-apt
.RI [ opciones ] " " [ orden ] " " [ args... ]
.SH DESCRIPCIÓN
Esta página del manual describe brevemente las órdenes de
.B auto-apt .
.PP
\fBauto-apt\fP es un programa que comprueba los accesos a ficheros de los
programas ejecutándose dentro de un entorno \fBauto-apt\fP. Si un programa
accede a un fichero de un paquete que no está instalado, \fBauto-apt\fP
instalará el paquete que contiene ese fichero usando apt-get.
.SH OPCIONES
A continuación se incluye un resumen de la opciones.
.TP
.B "-h"
Muestra el modo de uso.
.TP
.B "-s"
No realiza ninguna acción, realiza una simulación.
.TP
.B "-y"
Asume respuestas afirmativas.
.TP
.B "-q"
Modo silencioso.
.TP
.B "-i"
No realiza la instalación en segundo plano.
.TP
.B "-x"
Deshabilita la interfaz X.
.TP
.B "-X"
Habilita la interfaz X. Ejecuta apt-get en otro \fBx-terminal-emulator\fP 
si se ejecuta en un entorno X.
.TP
.BI "-a [" dist [, dist... ]]
Selecciona la distribución instalable de entre
.BR main , contrib , non-free , non-US
o
.B none.
Si usa "-a none", es igual que si usase la opción "-s".
.TP
.BI "-p [" enganche [, enganche... ]]
Selecciona las funciones de enganche de entre
.BR exec , open , access , stat
o
.B none
Si usa "-p none", es igual que si usase la opción "-s".
.TP
.BI "-D [" ficherodb ]
Usa \fIficherodb\fP en vez del predeterminado 
.B /var/cache/auto-apt/pkgcontents.db
.TP
.BI "-F [" ficherodb ]
Usa \fIficherodb\fP en vez del predeterminado
.B /var/cache/auto-apt/pkgfiles.db,
generado por la orden \fBauto-apt update-local\fP.
Es usado como \fIficherodb\fP predeterminado por órdenes con el sufijo
\fB-local\fP. En muchos casos se usa junto con la opción
.B -L
para detectar accesos de ficheros.
.TP
.BI "-L [" registro.lists ]
Añade los datos de acceso a los ficheros al fichero \fIregistro.lists\fP.

.SH ÓRDENES
A continuación se incluye un resumen de las órdenes.
.TP
.BI "run  [" orden ]
Ejecuta orden de forma controlada por \fPauto-apt\fP. Si \fIorden\fP no se
especifica, se usará el shell de usuario.
.TP
.B "update [" -a ]
Regenerar \fIficherodb\fP desde la información de sources.list.
El \fIficherodb\fP puede especificarse con la opción \fB-D\fP.
Con la opción \fB-a\fP, todos los ficheros se guardan en \fIficherodb\fP.
Dese cuenta de que el \fIficherodb\fP se vuelve muy grande con la opción
\fB-a\fP.
.TP
.B "update-local [" -a ]
Genera \fIficherodb\fP con la información de los paquetes instalados.  
\fficherodb\fP puede especificarse con la opción \fB-F\fP.
Con la opción \fB-a\fP, todos los ficheros se guardan en \fIficherodb\fP.
Dese cuenta de que el \fIficherodb\fP se vuelve muy grande con la opción
\fB-a\fP.
.TP
.B "merge [" -a ]
Combina la información de paquetes y ficheros en \fIficherodb\fP, que puede
especificarse con la opción \fB-D\fP.
Con la opción \fB-a\fP, todos los ficheros se guardan en \fIficherodb\fP.
Dese cuenta de que el \fIficherodb\fP se vuelve muy grande con la opción
\fB-a\fP.
.TP
.BI del " paquete "
Borra la información del \fIpaquete\fP de la base de datos del \fIficherodb\fP.
.TP
.BI check " " "[-v] [-f] " fichero
Comprueba que paquete proporciona \fIfichero\fP, usando la base de datos de
\fIficherodb\fP.
Opciones: \fB-v\fP mensajes explicativos. \fB-f\fP usa el fichero Contents-*.gz
en vez de la base de datos \fIficherodb\fP.
.TP
.BI install " " "[-s] [-d] [-u] [-y] [-v] " fichero
Intenta instalar el paquete que proporciona el \fIfichero\fP usando apt-get.
Necesita permisos de superusuario para ejecutar apt-get install.
.TP
.B list [-v] [-f]
Lista la información de la base de datos \fIficherodb\fP.
Opciones: \fB-v\fP mensajes explicativos. \fB-f\fP usa el fichero Contents-*.gz
en vez de la base de datos \fIficherodb\fP.
.TP
.BI search " " "[-v] [-f] " patrón
Busca información en el fichero usando
.BR grep (1)
\fIpatrón\fP en la base de datos \fIficherodb\fP.
Opciones: \fB-v\fP mensajes explicativos. \fB-f\fP usa el fichero Contents-*.gz
en vez de la base de datos \fIficherodb\fP.
.TP
.BI "debuild [" debuildopciones ]
Ejecuta 
.BR debuild (1)
en entornos auto-apt, y muestra una estimación de \fBBuild-Depends:\fP.
Se recomienda el uso de la opción \fB-s\fP de auto-apt.
.TP
.B status
Muestra si el entorno actual es un entorno \fBauto-apt\fP o no.
.\" .SH VÉASE ADEMÁS
.\" .BR auto-apt-pkgcdb (8)
.br
.SH FICHEROS
.IP o
/etc/auto-apt/paths\&.list
ruta de las listas.
.IP o
/var/cache/auto-apt
directorio de caché/base de datos.
.IP o
/etc/auto-apt/sources.list
sources.list para auto-apt. si no existe, se enlazará al sources.list de apt-get.
.\" .IP
.\" .IP o
.\" /etc/auto-apt/commands\&.list
.\" configuración de la orden (aún no implementado)
.SH ENTORNOS
.IP o
AUTO_APT_CACHEDIR
modifica el directorio de caché/base de datos por omisión.
.SH FALLOS
Para los fallos conocidos, vea
.B /usr/share/doc/auto-apt/BUGS.
y/o http://bugs.debian.org/auto-apt
.SH AUTOR
Este programa fue escrito por Fumitoshi UKAI <ukai@debian.or.jp>,
inspirado por la idea/comentarios de Debian Guru (debian.gr.jp) y
miembros de Project Dice.
.SH TRADUCTOR
Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>
