.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH auto-apt 1 "29 Jun 2000"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
auto-apt \- on demand package installation tool
.SH SYNOPSIS
.B auto-apt
.RI [ options ] " " [ command ] " " [ args... ]
.SH DESCRIPTION
This manual page documents briefly the
.B auto-apt
commands.
.PP
\fBauto-apt\fP is a program that checks file access of programs running
within \fBauto-apt\fP environments.  If a program will access a file of
uninstalled package, \fBauto-apt\fP will install the package containing
the file, by using apt-get.
.SH OPTIONS
A summary of options is included below.
.TP
.B "-h"
Usage.
.TP
.B "-s"
No action, perform a simulation of action.
.TP
.B "-y"
Automatic yes to prompt.
.TP
.B "-q"
Quiet
.TP
.B "-i"
Don't install in background process.
.TP
.B "-x"
Disable X interface.
.TP
.B "-X"
Enable X interface. Run apt-get in another \fBx-terminal-emulator\fP 
if you run in X environments.
.TP
.BI "-a [" dist [, dist... ]]
Select installable distribution from 
.BR main , contrib , non-free , non-US
or
.B none.
If you set "-a none", it means almost same as "-s".
.TP
.BI "-p [" hook [, hook... ]]
Select hook functions from
.BR exec , open , access , stat
or
.B none
If you set "-p none", it means almost same as "-s".
.TP
.BI "-D [" dbfile ]
Change \fIdbfile\fP from default 
.B /var/cache/auto-apt/pkgcontents.db
.TP
.BI "-F [" filedb ]
Change \fIfiledb\fP from default
.B /var/cache/auto-apt/pkgfiles.db,
which is generated by \fBauto-apt update-local\fP commands.
It is used as default \fIdbfile\fP for commands with \fB-local\fP 
postfix.  In many cases, it is used with 
.B -L
option to detect file access
.TP
.BI "-L [" record.lists ]
Append file access data to \fIrecord.lists\fP file.

.SH COMMANDS
A summary of command is included below. 
.TP
.BI "run  [" command ]
Run command controlled by \fPauto-apt\fP.  If \fIcommand\fP is not 
specified, user's shell will be used.  
.TP
.B "update [" -a ]
Recreate \fIdbfile\fP from sources.list information.
\fIdbfile\fP can be specified by \fB-D\fP option.
With \fB-a\fP option, all files are stored in \fIdbfile\fP.
Note that \fIdbfile\fP become too big with \fB-a\fP option.
.TP
.B "update-local [" -a ]
Generate \fIfiledb\fP from installed package information.  
\fIfiledb\fP can be specified by \fB-F\fP option.
With \fB-a\fP option, all files are stored in \fIdbfile\fP.
Note that \fIdbfile\fP become too big with \fB-a\fP option.
.TP
.B "merge [" -a ]
Merge package,filename information to \fIdbfile\fP, which can be
specified by \fB-D\fP option.
With \fB-a\fP option, all files are stored in \fIdbfile\fP.
Note that \fIdbfile\fP become too big with \fB-a\fP option.
.TP
.BI del " package "
Delete file information of \fIpackage\fP from \fIdbfile\fP database.
.TP
.BI check " " "[-v] [-f] " file
Check which package provides \fIfile\fP, from \fIdbfile\fP database.
options: \fB-v\fP means verbose. \fB-f\fP uses Contents-*.gz file
instead of \fIdbfile\fP database.
.TP
.BI install " " "[-s] [-d] [-u] [-y] [-v] " file
Try to install a package that provides \fIfile\fP by using apt-get.
You need root privilege to run apt-get install.
.TP
.B list [-v] [-f]
List file information in \fIdbfile\fP database.
options: \fB-v\fP means verbose. \fB-f\fP uses Contents-*.gz file
instead of \fIdbfile\fP database.
.TP
.BI search " " "[-v] [-f] " pattern
Search file information by 
.BR grep (1)
\fIpattern\fP in \fIdbfile\fP database.
options: \fB-v\fP means verbose. \fB-f\fP uses Contents-*.gz file
instead of \fIdbfile\fP database.
.TP
.BI "debuild [" debuildopts ]
Run 
.BR debuild (1)
in auto-apt environments, and show \fBBuild-Depends:\fP estimation.
Recommended to use with \fB-s\fP option of auto-apt.
.TP
.B status
Show whether current environment is in \fBauto-apt\fP or not.
.\" .SH SEE ALSO
.\" .BR auto-apt-pkgcdb (8)
.br
.SH FILES
.IP o
/etc/auto-apt/paths\&.list
path lists
.IP o
/var/cache/auto-apt
cache/database directory
.IP o
/etc/auto-apt/sources.list
sources.list for auto-apt. if not found, symlink to apt-get's sources.list
will be created.
.\" .IP
.\" .IP o
.\" /etc/auto-apt/commands\&.list
.\" command configuration (not yet implemented)
.SH ENVIRONMENTS
.IP o
AUTO_APT_CACHEDIR
override default cache/database directory
.SH BUGS
Known bugs. See 
.B /usr/share/doc/auto-apt/BUGS.
and/or http://bugs.debian.org/auto-apt
.SH AUTHOR
This program was written by Fumitoshi UKAI <ukai@debian.or.jp>,
inspired by idea/comments from Debian Guru (debian.gr.jp) and 
Project Dice members.
